# Generated by Django 5.1.1 on 2024-09-30 09:00

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import userLogin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('email', models.EmailField(default='Email', max_length=150, unique=True)),
                ('dob', models.DateField(default='ddmmyy')),
                ('designation', models.CharField(default='UGMT Member', max_length=100)),
                ('gender', models.CharField(default='Gender', max_length=10)),
                ('blood_group', models.CharField(default='Blood Group', max_length=5)),
                ('state', models.CharField(default='State', max_length=100)),
                ('district', models.CharField(default='District', max_length=100)),
                ('zip_code', models.CharField(default='000000', max_length=6)),
                ('address', models.TextField(default='Address')),
                ('near_by', models.TextField(default='nearBy')),
                ('mobile', models.CharField(default='Mobile', max_length=10)),
                ('mobile_home', models.CharField(blank=True, default='MobileHome', max_length=10, null=True)),
                ('aadhar', models.CharField(default='AadharNumber', max_length=15, unique=True)),
                ('aadharPhoto', models.ImageField(default='', upload_to=userLogin.models.aadharPic)),
                ('profilePic', models.ImageField(default='defaultProfile.png', upload_to=userLogin.models.profile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('nominee1_name', models.CharField(default='Nominee1-Name', max_length=200)),
                ('nominee1_mobile', models.CharField(blank=True, default='Nominee1-Mobile', max_length=20, null=True)),
                ('nominee1_aadhar', models.CharField(blank=True, default='Nominee1-Aadhar', max_length=100, null=True)),
                ('nominee1_relation', models.CharField(blank=True, default='Nominee1-Relation', max_length=20, null=True)),
                ('nominee2_name', models.CharField(default='Nominee2-Name', max_length=200)),
                ('nominee2_mobile', models.CharField(blank=True, default='Nominee2-Mobile', max_length=20, null=True)),
                ('nominee2_aadhar', models.CharField(blank=True, default='Nominee2-Aadhar', max_length=100, null=True)),
                ('nominee2_relation', models.CharField(blank=True, default='Nominee2-Relation', max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('registerDate', models.DateField(verbose_name=datetime.datetime(2024, 9, 30, 9, 0, 27, 440777, tzinfo=datetime.timezone.utc))),
                ('expiring_Date', models.DateField(verbose_name=datetime.datetime(2025, 9, 30, 9, 0, 27, 440793, tzinfo=datetime.timezone.utc))),
                ('password', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text_area', models.TextField()),
                ('bank_name', models.CharField(default='Bank Name', max_length=200)),
                ('upi_id', models.CharField(default='UPI ID', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_per_member', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('donation_status', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorAlert', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonatedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('charity_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='userLogin.charityalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationTransactionID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_matched', models.BooleanField(default=False)),
                ('charity_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_request', to='userLogin.charityalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notice_text', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorNotice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
