# Generated by Django 5.1.1 on 2024-09-30 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_alter_user_expiring_date_alter_user_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiring_Date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 9, 30, 9, 0, 48, 270283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registerDate',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 30, 9, 0, 48, 270259, tzinfo=datetime.timezone.utc)),
        ),
    ]
