# Generated by Django 5.0.4 on 2026-03-16 09:44

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import userLogin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userLogin", "0003_alter_user_expiring_date_alter_user_registerdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustDonationID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(default="Name", max_length=200)),
                ("mobile", models.CharField(default="Mobile", max_length=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("is_matched", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="nominee1_aadhar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nominee2_aadhar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nominee2_mobile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nominee2_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nominee2_relation",
        ),
        migrations.AddField(
            model_name="charityalert",
            name="receiverNominee",
            field=models.CharField(default="NomineeAadhar", max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="chronic_disease",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="home_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="refer_id",
            field=models.CharField(
                blank=True, default="Refer id", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="refer_mobile",
            field=models.CharField(
                blank=True, default="Refer Mobile", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="refer_name",
            field=models.CharField(default="Refer Name", max_length=200),
        ),
        migrations.AlterField(
            model_name="charityalert",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="aadharPhoto",
            field=models.ImageField(
                default="defaultProfile.png", upload_to=userLogin.models.aadharPic
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="expiring_Date",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2027, 3, 16, 9, 44, 37, 9877, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_home",
            field=models.CharField(
                blank=True, default="Mobile", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registerDate",
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="NGOPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NGOMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        upload_to=userLogin.models.ngo_media_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="userLogin.ngopost",
                    ),
                ),
            ],
        ),
    ]
